import Navbar from '@/components/Common/Navbar'

import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import './globals.css'

const InstFont = Instrument_Sans({
    variable: '--font-inst',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="bg-base-100" data-theme="corporate">
            <body className={`${InstFont.className}  antialiased `}>
                {/* <Navbar className={containerClasses} /> */}
                {children}
            </body>
        </html>
    )
}
