import Navbar from '@/components/Common/Navbar'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const InterFont = Inter({
    variable: '--font-inter',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const containerClasses = 'px-4 sm:px-6 lg:px-8 max-w-screen-xl mx-auto'

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="bg-base-200">
            <body className={`${InterFont.className}  antialiased `}>
                <Navbar className={containerClasses} />
                <main className={`${containerClasses} py-8`}>{children}</main>
            </body>
        </html>
    )
}
